//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutesGMAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public int Manufacturer_id { get; set; }
        public string ManufacturerName { get; set; }
        public string ManufacturerAdress { get; set; }
    }
}
