//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutesGMAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Product_id { get; set; }
        public string ProductName { get; set; }
        public int ProductCategory { get; set; }
        public Nullable<int> ProductManufacturer { get; set; }
        public string ProductVolume { get; set; }
    }
}
