//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutesGMAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopsAdress
    {
        public int Shop_id { get; set; }
        public string ShopAdress { get; set; }
        public Nullable<double> ShopLatitude { get; set; }
        public Nullable<double> ShopLongitude { get; set; }
        public int Id { get; set; }
    }
}
